### EDA

In [1]:
#importing pandas library
import pandas as pd

In [2]:
# python package installer
!pip install pandas

Requirement already satisfied: pandas in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# importing dataset
df = pd.read_csv("customer_shopping_behavior (1).csv")

In [4]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [6]:
len(df)

5050

In [7]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [8]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5050.000000,5050.000000,5050,5050,5050,4494.000000,5050,4680,5050,5050,4449.000000,5050,5050,5050,4502.000000,5050,5050
unique,NaN,NaN,3,30,5,NaN,54,4,25,5,NaN,2,6,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,NaN,NaN,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,2519.570891,44.150495,NaN,NaN,NaN,144.765236,NaN,NaN,NaN,NaN,3.668195,NaN,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,NaN,275.590101,NaN,NaN,NaN,NaN,0.865357,NaN,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.120000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,NaN,89.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   str
 3   Item Purchased          5050 non-null   str
 4   Category                5050 non-null   str
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   str
 7   Size                    4680 non-null   str
 8   Color                   5050 non-null   str
 9   Season                  5050 non-null   str
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   str
 12  Shipping Type           5050 non-null   str
 13  Discount Applied        5050 non-null   str
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   str
 16  Frequency of Purchases  5050 non-null   str
dtypes: float64(3), int64(2), str(12)
memory usage: 670.8 KB

In [10]:
#checking the null count
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

### Data cleaning

In [11]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [12]:
df['Item Purchased']

0          T-shirt
1       Sunglasses
2            Shirt
3           Gloves
4          Jewelry
           ...
5045        Hoodie
5046      Backpack
5047         Skirt
5048      Sneakers
5049        Blouse
Name: Item Purchased, Length: 5050, dtype: str

In [13]:
df['Item Purchased'].unique()

<StringArray>
[   'T-shirt', 'Sunglasses',      'Shirt',     'Gloves',    'Jewelry',
     'Shorts',        'Hat',    'Handbag',      'Shoes',       'Coat',
     'Laptop',     'Hoodie',      'Phone',     'Jacket',      'Pants',
   'Backpack',      'Socks',      'Jeans',        'Bag',       'Belt',
      'Watch', 'Headphones',     'Blouse',    'Sandals',      'Skirt',
    'Sweater',      'Scarf',   'Sneakers',      'Boots',      'Dress']
Length: 30, dtype: str

In [14]:
df['Category'].unique()

<StringArray>
['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear']
Length: 5, dtype: str

In [15]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [16]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [17]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [18]:
correct_mapping = {
    # Clothing
    "T-shirt": "Clothing", "Shirt":"Clothing","Shorts":"Clothing",
    "Hoodie":"Clothing", "Pants":"Clothing", "Socks":"Clothing",
    "Jeans": "Clothing", "Blouse":"Clothing", "Skirt":"Clothing",
    "Sweater": "Clothing", "Dress":"Clothing",

    # Accessories
    "Sunglasses": "Accessories", "Gloves":"Accessories",
    "Jewelry": "Accessories", "Hat": "Accessories",
    "Handbag": "Accessories", "Backpack": "Accessories",
    "Belt": "Accessories", "Scarf": "Accessories",
    "Bag": "Accessories",

    # Electronics
    "Laptop": "Electronics", "Phone": "Electronics",
    "Headphones": "Electronics", "Watch":  "Electronics",

    # Footwear
    "Shoes": "Footwear", "Sandals": "Footwear",
    "Sneakers": "Footwear", "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear"
}

In [19]:
df['Category'] = df['Item Purchased'].map(correct_mapping)

In [20]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

### Treating the null values

In [21]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [22]:
df['Size'].unique()

<StringArray>
['XL', 'M', 'L', 'S', nan]
Length: 5, dtype: str

In [23]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [24]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [25]:
#Treating the null values or replacing all values in electronic category
df.loc[df['Category']== 'Electronics','Size'] = "Not Applicable"

In [26]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [27]:
df.loc[df['Category']== 'Accessories','Size'] = "Free Size"

In [28]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [29]:
df.loc[df['Category']== 'Footwear','Size'] = "Not Applicable"

In [30]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear         [Not Applicable]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [31]:
#Treating the null values or replacing all values in electronic category
df.loc[(df['Category']=='Clothing') & (df['Size'].isnull()),'Size'] = df[df["Category"] == "Clothing"]["Size"].mode()[0]

In [32]:
df.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear       [Not Applicable]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [33]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [34]:
# mean of review rating
df['Review Rating'].mean()

np.float64(3.668195100022477)

In [35]:
# median of review rating
df['Review Rating'].median()

np.float64(3.7)

In [36]:
# mode of review rating
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [37]:
df.groupby('Item Purchased')['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [38]:
# Filling the null values of Review Ratings with the mean of each Item Purchased
df['Review Rating'] = df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [39]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [40]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.200000,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.900000,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.100000,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.200000,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.600000,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.400000,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.790541,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,Free Size,Purple,Summer,4.000000,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,Free Size,Red,Spring,4.300000,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,Free Size,Yellow,Winter,2.800000,Yes,Store Pickup,Yes,7.0,Cash,Monthly

In [41]:
df['Review Rating'] = df['Review Rating'].round(2)

In [42]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.20,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.90,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.10,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.20,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.60,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.40,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.79,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,Free Size,Purple,Summer,4.00,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,Free Size,Red,Spring,4.30,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,Free Size,Yellow,Winter,2.80,Yes,Store Pickup,Yes,7.0,Cash,Monthly

### Previous Purchase

In [43]:
df['Previous Purchases'].unique()

array([36., 20., 18., 25., 17., 15.,  2., 28.,  7., 41.,  4., nan, 30.,
       33., 39., 13.,  6., 50., 24.,  8.,  5., 45., 31., 16., 47., 37.,
        1., 34., 12.,  0.,  9., 27., 40., 26., 32., 48., 38., 22., 29.,
       11., 44., 35., 19., 10., 14.,  3., 49., 46., 43., 42., 21., 23.])

In [44]:
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

In [45]:
df['Previous Purchases'].unique()

array([36., 20., 18., 25., 17., 15.,  2., 28.,  7., 41.,  4.,  0., 30.,
       33., 39., 13.,  6., 50., 24.,  8.,  5., 45., 31., 16., 47., 37.,
        1., 34., 12.,  9., 27., 40., 26., 32., 48., 38., 22., 29., 11.,
       44., 35., 19., 10., 14.,  3., 49., 46., 43., 42., 21., 23.])

In [46]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

### Purchase Amount

In [47]:
df.groupby('Item Purchased')['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [48]:
df['Purchase Amount (USD)'] = df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [49]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

### Checking Duplicate Values

In [50]:
df.duplicated().sum()

np.int64(50)

In [51]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free Size,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,Not Applicable,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,Not Applicable,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Free Size,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Free Size,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Free Size,Peach,Summer,3.70,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Free Size,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Free Size,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Free Size,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Free Size,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Free Size,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,Not Applicable,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,Not Applicable,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,Not Applicable,Red,Winter,3.81,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Free Size,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Free Size,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,Not Applicable,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Free Size,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Free Size,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Free Size,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Free Size,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,Not Applicable,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Free Size,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Free Size,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,Not Applicable,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly

In [52]:
df[df['Customer ID'] == 974]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
483,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly

In [53]:
len(df)

5050

In [54]:
#Deleting Duplicate Records
df = df.drop_duplicates(subset = ['Customer ID'],keep = 'first')

In [55]:
len(df)

5000

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.count()

Customer ID               5000
Age                       5000
Gender                    5000
Item Purchased            5000
Category                  5000
Purchase Amount (USD)     5000
Location                  5000
Size                      5000
Color                     5000
Season                    5000
Review Rating             5000
Subscription Status       5000
Shipping Type             5000
Discount Applied          5000
Previous Purchases        5000
Payment Method            5000
Frequency of Purchases    5000
dtype: int64

In [58]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [59]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='str')

### Renaming the headers

In [60]:
df.columns = df.columns.str.replace(" ","_")

In [61]:
df.columns = df.columns.str.lower()

In [62]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [63]:
# Replacing purchase_amount_(usd) to purchase_amount
df = df.rename(columns = {"purchase_amount_(usd)":"purchase_amount"})

In [64]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [65]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

### Connection to SQL server

In [66]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Connection to MYSQL workbench

In [67]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.1.3)
Requirement already satisfied: sqlalchemy in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\mesuh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:
import cryptography
print("Installed successfully")

Installed successfully

In [72]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Amisha%40123@localhost:3306/customerdb"
)

connection = engine.connect()

print("Connected Successfully!")

Connected Successfully!

In [73]:
df.to_sql(
    name='shopping_data',
    con=engine,
    if_exists='replace',
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!

In [74]:
df

      customer_id  age  gender item_purchased     category  purchase_amount  \
0            2701   22  Female        T-shirt     Clothing        68.000000
1             521   51    Male     Sunglasses  Accessories        84.000000
2            3157   18  Female          Shirt     Clothing        50.000000
3            1687   22    Male         Gloves  Accessories        75.000000
4            2929   40  Female        Jewelry  Accessories        80.000000
5            3583   23  Female         Shorts     Clothing        41.000000
6            1135   62    Male        T-shirt     Clothing        81.000000
7            1411   61    Male            Hat  Accessories        93.000000
8             113   37    Male         Gloves  Accessories        65.000000
9             166   42    Male        Handbag  Accessories        60.000000
10           4568   35   Other          Shoes     Footwear       276.343790
11            947   46    Male           Coat    Outerwear        24.000000
12           4776   64   Other         Laptop  Electronics       884.040000
13           3855   57  Female        T-shirt     Clothing        20.000000
14            481   68    Male         Hoodie     Clothing        88.000000
15           3790   56  Female          Shirt     Clothing        75.000000
16           3617   42  Female         Hoodie     Clothing        23.000000
17           2659   52  Female        Handbag  Accessories        47.000000
18           3725   30  Female         Gloves  Accessories        71.000000
19           2134   21    Male            Hat  Accessories        34.000000
20           4256   70    Male          Phone  Electronics       734.477349
21            833   58    Male         Jacket    Outerwear        80.000000
22           1106   33    Male        T-shirt     Clothing        83.000000
23           3047   60  Female          Shoes     Footwear        49.000000
24           4685   68   Other          Phone  Electronics      1032.090000
25           1612   41    Male          Pants     Clothing        26.000000
26           4289   34  Female          Phone  Electronics      1282.440000
27           3552   66  Female         Gloves  Accessories        31.000000
28           2918   58  Female          Shirt     Clothing        45.000000
29           1192   34    Male        T-shirt     Clothing        70.000000
30           1907   23    Male       Backpack  Accessories        30.000000
31           1332   38    Male          Socks     Clothing        91.000000
32            316   66    Male        Jewelry  Accessories        24.000000
33            347   49    Male          Jeans     Clothing        50.000000
34           3115   21  Female        Handbag  Accessories        56.000000
35           5042   46   Other            Bag  Accessories       735.773625
36           1498   69    Male         Jacket    Outerwear        33.000000
37           1606   70    Male           Belt  Accessories        46.000000
38           4418   67  Female          Watch  Electronics       685.231471
39           4894   24   Other            Bag  Accessories       735.773625
40           4576   65    Male     Headphones  Electronics       831.344565
41           2486   43    Male         Blouse     Clothing        55.000000
42            187   39    Male       Backpack  Accessories        56.000000
43            275   59    Male        Jewelry  Accessories        32.000000
44           1402   23    Male        Sandals     Footwear        59.000000
45           1181   23    Male          Skirt     Clothing        23.000000
46           2130   40    Male          Skirt     Clothing        57.000000
47            995   53    Male          Shoes     Footwear        68.000000
48           1230   34    Male        Jewelry  Accessories        52.000000
49           4319   47   Other          Watch  Electronics       685.231471
50           4489   36  Female          Phone  Electronics       748.610000
51           4708   33  Female            Bag  Accessories       735.773625
52           4827   20  Female         Laptop  Electronics       805.502027
53           1348   44    Male        Sweater     Clothing        95.000000
54           4584   55  Female          Watch  Electronics       685.231471
55           3116   26  Female          Scarf  Accessories        53.000000
56           1168   60    Male          Socks     Clothing        83.000000
57           3685   29  Female          Skirt     Clothing        86.000000
58           4111   49    Male          Phone  Electronics       734.477349
59           2850   56  Female           Coat    Outerwear        25.000000
60           1636   68    Male     Sunglasses  Accessories        24.000000
61           1489   23    Male            Hat  Accessories        44.000000
62           3827   50  Female         Jacket    Outerwear        31.000000
63           2417   59    Male        Sandals     Footwear        83.000000
64           2832   34  Female         Hoodie     Clothing        53.000000
65           4607   47   Other          Shirt     Clothing       557.240000
66           2367   30    Male          Shoes     Footwear        66.000000
67           4851   42  Female          Watch  Electronics       685.231471
68            508   65    Male         Shorts     Clothing        20.000000
69           4845   19  Female          Shirt     Clothing       692.110000
70           2098   33    Male       Sneakers     Footwear        43.000000
71           1080   18    Male           Coat    Outerwear        33.000000
72           4558   41   Other            Bag  Accessories       208.020000
73           4492   59  Female         Laptop  Electronics       805.502027
74           4292   27   Other         Laptop  Electronics       805.502027
75           3036   69  Female        Handbag  Accessories        64.000000
76           3554   62  Female          Shoes     Footwear        99.000000
77           2077   59    Male         Gloves  Accessories        23.000000
78           3088   62  Female          Shirt     Clothing        84.000000
79           3739   34  Female         Shorts     Clothing        45.000000
80           3309   55  Female          Jeans     Clothing        70.000000
81           2922   20  Female        Handbag  Accessories        24.000000
82           4156   51   Other          Shirt     Clothing      1398.900000
83           4869   26  Female     Headphones  Electronics       500.300000
84            660   62    Male         Shorts     Clothing        52.000000
85           3632   48  Female            Hat  Accessories        50.000000
86           3217   39  Female         Hoodie     Clothing        85.000000
87           3696   38  Female          Skirt     Clothing        33.000000
88            146   24    Male        Jewelry  Accessories        95.000000
89            693   35    Male     Sunglasses  Accessories        95.000000
90           1837   66    Male          Pants     Clothing        52.000000
91            598   70    Male        Jewelry  Accessories        69.000000
92            165   59    Male        Handbag  Accessories        65.000000
93           1186   47    Male          Jeans     Clothing        64.000000
94           3328   47  Female         Shorts     Clothing        64.000000
95           4404   67    Male          Watch  Electronics       498.030000
96           4153   67   Other          Shoes     Footwear       276.343790
97           4587   52    Male         Laptop  Electronics      1392.020000
98           4057   41  Female          Shoes     Footwear       276.343790
99           3889   45  Female       Sneakers     Footwear        69.000000
100           106   69    Male       Backpack  Accessories        96.000000
101          4176   23    Male          Shoes     Footwear       390.250000
102            63   30    Male       Sneakers     Footwear        21.000000
103          3455   55  Female        Handbag  Accessories        71.000000
104          2500   52    Male         Hoodie     Clothing        73.000000
105          2136   34    Male     Sunglasses  Accessories        94.000000
106          3584   52  Female         Blouse     Clothing        77.000000
107          4118   18   Other          Shirt     Clothing       279.935608
108          2547   63    Male          Boots     Footwear        21.000000
109          4972   46   Other            Bag  Accessories        34.650000
110          3365   50  Female          Scarf  Accessories        33.000000
111          1637   58    Male          Boots     Footwear        22.000000
112          2000   39    Male          Socks     Clothing        89.000000
113          2603   65    Male           Coat    Outerwear        44.000000
114          2700   25  Female          Boots     Footwear        96.000000
115          4189   38    Male          Shoes     Footwear      1312.350000
116          3371   30  Female           Belt  Accessories        31.000000
117          3599   23  Female         Hoodie     Clothing        76.000000
118          4072   63    Male          Shoes     Footwear       276.343790
119          1432   39    Male          Pants     Clothing        88.000000
120          2381   41    Male          Scarf  Accessories        66.000000
121          2120   58    Male        Jewelry  Accessories        57.000000
122          3502   53  Female          Shoes     Footwear        87.000000
123          3551   63  Female          Shoes     Footwear        74.000000
124           712   64    Male          Boots     Footwear        60.000000
125          1337   23    Male       Sneakers     Footwear        85.000000
126          1047   40    Male       Sneakers     Footwear        22.000000
127          2225   18    Male         Gloves  Accessories        25.000000
128          3525   69  Female          Pants     Clothing        74.000000
129          4530   20    Male          Watch  Electronics       532.490000
130          3199   61  Female         Gloves  Accessories        94.000000
131            70   48    Male           Belt  Accessories        70.000000
132          2721   55  Female          Scarf  Accessories        52.000000
133           436   51    Male           Coat    Outerwear        28.000000
134           387   64    Male        Jewelry  Accessories        39.000000
135          3867   58  Female            Hat  Accessories        32.000000
136          3358   41  Female         Hoodie     Clothing        67.000000
137           608   47    Male         Hoodie     Clothing        23.000000
138           115   70    Male           Coat    Outerwear        95.000000
139          4712   60    Male         Laptop  Electronics        95.150000
140          5058   63   Other          Shirt     Clothing      1342.620000
141          2568   19    Male     Sunglasses  Accessories        25.000000
142          4381   53  Female          Watch  Electronics       685.231471
143          4192   46   Other          Watch  Electronics       105.210000
144           235   20    Male         Gloves  Accessories        39.000000
145          3699   25  Female          Skirt     Clothing        54.000000
146          3215   53  Female          Skirt     Clothing        78.000000
147          1876   63    Male          Boots     Footwear        71.000000
148          1625   38    Male        Sweater     Clothing        32.000000
149          1396   47    Male          Scarf  Accessories        32.000000
150             9   26    Male           Coat    Outerwear        97.000000
151          2168   30    Male          Skirt     Clothing        48.000000
152           749   35    Male            Hat  Accessories        39.000000
153          2507   57    Male          Dress     Clothing        82.000000
154          1285   65    Male          Dress     Clothing        93.000000
155          4047   49    Male          Watch  Electronics       685.231471
156          5014   60  Female          Shirt     Clothing       279.935608
157          1195   50    Male         Hoodie     Clothing        46.000000
158          2013   48    Male          Jeans     Clothing        53.000000
159          4076   57   Other          Watch  Electronics       685.231471
160          2050   68    Male          Boots     Footwear        24.000000
161          1306   31    Male          Pants     Clothing        56.000000
162          5024   38   Other            Bag  Accessories       735.773625
163          3170   35  Female        T-shirt     Clothing        59.000000
164          1116   30    Male            Hat  Accessories        58.000000
165          2317   28    Male       Sneakers     Footwear        39.000000
166           728   62    Male        Sweater     Clothing        97.000000
167           467   38    Male          Jeans     Clothing        24.000000
168          4235   56   Other     Headphones  Electronics       831.344565
169           656   20    Male        Handbag  Accessories        36.000000
170          4542   28   Other          Shoes     Footwear       276.343790
171            99   20    Male          Jeans     Clothing        67.000000
172          3681   22  Female     Sunglasses  Accessories        36.000000
173          3715   18  Female            Hat  Accessories        31.000000
174          2726   64  Female       Backpack  Accessories        99.000000
175          2544   27    Male          Scarf  Accessories        56.000000
176          2834   43  Female          Jeans     Clothing        56.000000
177          1084   35    Male       Backpack  Accessories        97.000000
178          2904   38  Female          Scarf  Accessories        39.000000
179           964   21    Male          Boots     Footwear        63.000000
180           299   69    Male        T-shirt     Clothing        53.000000
181          1327   40    Male          Shoes     Footwear        50.000000
182          2789   56  Female          Boots     Footwear        92.000000
183          2321   28    Male          Shoes     Footwear        55.000000
184            79   50    Male          Skirt     Clothing        91.000000
185           771   19    Male       Sneakers     Footwear        54.000000
186          1543   59    Male         Blouse     Clothing        44.000000
187          2223   32    Male          Pants     Clothing        66.000000
188          3461   41  Female          Scarf  Accessories        78.000000
189          1952   33    Male         Gloves  Accessories        53.000000
190          4552   57    Male          Shoes     Footwear       276.343790
191          1645   68    Male           Coat    Outerwear        90.000000
192           510   41    Male        T-shirt     Clothing        80.000000
193          2854   37  Female            Hat  Accessories        48.000000
194           378   63    Male          Scarf  Accessories        32.000000
195           827   54    Male          Dress     Clothing        94.000000
196          4571   40   Other          Shirt     Clothing       450.410000
197           546   33    Male           Coat    Outerwear        32.000000
198          2085   32    Male         Blouse     Clothing        94.000000
199           641   53    Male          Skirt     Clothing        88.000000
200          5037   41  Female          Watch  Electronics       685.231471
201          4843   22  Female          Phone  Electronics       854.960000
202          1771   53    Male       Backpack  Accessories        22.000000
203          1861   18    Male        T-shirt     Clothing        64.000000
204          4011   50  Female     Headphones  Electronics       831.344565
205          2915   45  Female        Sweater     Clothing        72.000000
206          5009   35    Male          Watch  Electronics       585.100000
207          5083   42   Other          Shoes     Footwear       758.100000
208          2990   46  Female           Belt  Accessories        20.000000
209          4079   28    Male          Shoes     Footwear      1438.530000
210          2056   28    Male        Handbag  Accessories        33.000000
211          1994   32    Male         Blouse     Clothing        96.000000
212          4257   60   Other            Bag  Accessories       735.773625
213          2347   22    Male         Jacket    Outerwear        67.000000
214          3063   51  Female       Backpack  Accessories        96.000000
215          1967   67    Male         Jacket    Outerwear        95.000000
216          2131   25    Male       Backpack  Accessories        68.000000
217          4171   23    Male          Phone  Electronics       495.980000
218           818   25    Male        Handbag  Accessories        21.000000
219          3336   44  Female            Hat  Accessories        94.000000
220          2100   31    Male        T-shirt     Clothing        78.000000
221           383   28    Male          Jeans     Clothing        76.000000
222          4991   29   Other         Laptop  Electronics      1366.100000
223          1592   18    Male          Skirt     Clothing       100.000000
224          4077   33    Male          Shoes     Footwear       276.343790
225          3127   57  Female     Sunglasses  Accessories        76.000000
226          3759   61  Female        Sandals     Footwear        54.000000
227          1877   54    Male          Skirt     Clothing        36.000000
228          4896   24  Female          Watch  Electronics       685.231471
229          1564   68    Male          Pants     Clothing        44.000000
230          1610   33    Male          Shirt     Clothing        93.000000
231           148   63    Male          Shoes     Footwear        64.000000
232          2946   32  Female           Belt  Accessories        49.000000
233           149   37    Male         Gloves  Accessories        90.000000
234          5095   57  Female          Shirt     Clothing       279.935608
235          2564   69    Male       Backpack  Accessories        81.000000
236           470   21    Male         Shorts     Clothing        46.000000
237          2027   37    Male          Scarf  Accessories        35.000000
238          2957   52  Female          Dress     Clothing        88.000000
239          1995   33    Male     Sunglasses  Accessories        66.000000
240          4933   44   Other         Laptop  Electronics       805.502027
241           111   56    Male       Backpack  Accessories        26.000000
242          1010   39    Male         Hoodie     Clothing        30.000000
243          4355   46  Female          Shoes     Footwear       585.850000
244          4743   65  Female         Laptop  Electronics       772.940000
245           585   70    Male          Socks     Clothing        94.000000
246           976   58    Male        Sweater     Clothing        40.000000
247          2287   67    Male          Socks     Clothing        38.000000
248          1978   24    Male        Sandals     Footwear        49.000000
249          4741   23    Male          Phone  Electronics       734.477349
250          2228   40    Male          Scarf  Accessories        74.000000
251          2019   60    Male       Backpack  Accessories        97.000000
252          5027   39    Male     Headphones  Electronics      1430.070000
253          5082   56  Female          Watch  Electronics      1186.980000
254          4249   19   Other          Watch  Electronics       685.231471
255           638   21    Male        Sweater     Clothing        20.000000
256          3357   39  Female          Jeans     Clothing        48.000000
257           777   49    Male          Shirt     Clothing        60.000000
258          2439   32    Male          Jeans     Clothing        20.000000
259          2690   29  Female         Blouse     Clothing        35.000000
260          2552   29    Male          Shoes     Footwear        32.000000
261          4424   69   Other     Headphones  Electronics      1223.830000

In [ ]:
df.to_csv("cleaned.csv",inde=False)